{
	"id": "oval:org.opensuse.security:def:20141624",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2014-1624",
		"affected": {
			"family": "unix",
			"platform": [
				"SUSE Linux Enterprise Desktop 12",
				"SUSE Linux Enterprise Desktop 12 SP4"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2014-1624",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1624",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2014-1624",
				"ref_url": "https://www.suse.com/security/cve/CVE-2014-1624",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SU-2019:2719-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2019-October/006030.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2019:2719-2",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2019-November/006123.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    Race condition in the xdg.BaseDirectory.get_runtime_dir function in python-xdg 0.25 allows local users to overwrite arbitrary files by pre-creating /tmp/pyxdg-runtime-dir-fallback-victim to point to a victim-owned location, then replacing it with a symlink to an attacker-controlled location once the get_runtime_dir function is called.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Low",
			"cve": [
				{
					"text": "CVE-2014-1624",
					"href": "https://www.suse.com/security/cve/CVE-2014-1624/",
					"impact": "low",
					"cvss3": "4/CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 859835",
					"href": "https://bugzilla.suse.com/859835"
				}
			],
			"issued": {
				"date": "2021-04-30"
			},
			"updated": {
				"date": "2022-03-01"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:suse:sled:12",
					"cpe:/o:suse:sled:12:sp4"
				]
			}
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009116183",
						"comment": "SUSE Linux Enterprise Desktop 12 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009334348",
						"comment": "python-xdg is not affected"
					}
				]
			},
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009239879",
						"comment": "SUSE Linux Enterprise Desktop 12 SP4 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009522258",
						"comment": "python-xdg-0.25-9.3.1 is installed"
					}
				]
			}
		]
	}
}
