{
	"id": "oval:org.opensuse.security:def:20240397",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2024-0397",
		"affected": {
			"family": "unix",
			"platform": [
				"SUSE Linux Enterprise Micro 6.1"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2024-0397",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-0397",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2024-0397",
				"ref_url": "https://www.suse.com/security/cve/CVE-2024-0397",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SU-202410:15282-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-November/019829.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-202410:15283-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-November/019828.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:2249-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-July/018832.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:2274-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-July/018852.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:2280-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-July/018854.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:2479-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2024-July/036005.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:2572-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2024-July/036102.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:2982-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2024-August/036645.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:4020-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-November/019831.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:4021-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-November/019830.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:4025-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-November/019827.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:4026-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-November/019826.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:4029-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-November/019825.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    A defect was discovered in the Python \"ssl\" module where there is a memory\nrace condition with the ssl.SSLContext methods \"cert_store_stats()\" and\n\"get_ca_certs()\". The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Moderate",
			"cve": [
				{
					"text": "CVE-2024-0397 at SUSE",
					"href": "https://www.suse.com/security/cve/CVE-2024-0397/",
					"impact": "medium",
					"cvss3": "4.8/CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:L"
				},
				{
					"text": "CVE-2024-0397 at NVD",
					"href": "https://nvd.nist.gov/vuln/detail/CVE-2024-0397"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1226447",
					"href": "https://bugzilla.suse.com/1226447"
				}
			],
			"issued": {
				"date": "2024-11-24"
			},
			"updated": {
				"date": "2024-11-24"
			},
			"affected_cpe_list": {}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009954414",
						"comment": "libpython3_11-1_0-3.11.8-slfo.1.1_3.12 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009954415",
						"comment": "python311-3.11.8-slfo.1.1_3.3 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009954416",
						"comment": "python311-base-3.11.8-slfo.1.1_3.12 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009954417",
						"comment": "python311-curses-3.11.8-slfo.1.1_3.3 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009954035",
				"comment": "SUSE Linux Enterprise Micro 6.1 is installed"
			}
		]
	}
}
