{
	"id": "oval:org.opensuse.security:def:201718342",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2017-18342",
		"affected": {
			"family": "unix",
			"platform": [
				"SUSE Linux Enterprise Micro 6.1"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2017-18342",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2017-18342",
				"ref_url": "https://www.suse.com/security/cve/CVE-2017-18342",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-FU-2022:0444-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2022-February/021718.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-FU-2022:0445-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2022-February/021715.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-FU-2022:0447-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2022-February/021720.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-FU-2022:0450-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2022-February/021717.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-FU-2022:0452-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2022-February/021719.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-FU-2022:0454-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2022-February/021714.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-FU-2022:0456-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2022-February/021716.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "unknown",
				"ref_url": "https://lists.suse.com/pipermail/neuvector-updates/2023-November/000021.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    In PyYAML before 5.1, the yaml.load() API could execute arbitrary code if used with untrusted data. The load() function has been deprecated in version 5.1 and the 'UnsafeLoader' has been introduced for backward compatibility with the function.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Important",
			"cve": [
				{
					"text": "CVE-2017-18342 at SUSE",
					"href": "https://www.suse.com/security/cve/CVE-2017-18342/",
					"impact": "high",
					"cvss3": "7.4/CVSS:3.0/AV:L/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
				},
				{
					"text": "CVE-2017-18342 at NVD",
					"href": "https://nvd.nist.gov/vuln/detail/CVE-2017-18342",
					"impact": "critical",
					"cvss3": "9.8/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1099308",
					"href": "https://bugzilla.suse.com/1099308"
				},
				{
					"text": "SUSE bug 1164453",
					"href": "https://bugzilla.suse.com/1164453"
				}
			],
			"issued": {
				"date": "2024-11-24"
			},
			"updated": {
				"date": "2024-11-24"
			},
			"affected_cpe_list": {}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009954035",
				"comment": "SUSE Linux Enterprise Micro 6.1 is installed"
			},
			{
				"test_ref": "oval:org.opensuse.security:tst:2009954579",
				"comment": "python311-PyYAML-6.0.1-slfo.1.1_1.2 is installed"
			}
		]
	}
}
