{
	"id": "oval:org.opensuse.security:def:202438355",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2024-38355",
		"affected": {
			"family": "unix",
			"platform": [
				"SUSE Linux Enterprise Desktop 15 SP6",
				"SUSE Linux Enterprise High Performance Computing 15 SP6",
				"SUSE Linux Enterprise Module for Python 3 15 SP6",
				"SUSE Linux Enterprise Server 15 SP6",
				"SUSE Linux Enterprise Server for SAP Applications 15 SP6"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2024-38355",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-38355",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2024-38355",
				"ref_url": "https://www.suse.com/security/cve/CVE-2024-38355",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SU-2024:3771-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-October/019689.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    Socket.IO is an open source, real-time, bidirectional, event-based, communication framework. A specially crafted Socket.IO packet can trigger an uncaught exception on the Socket.IO server, thus killing the Node.js process. This issue is fixed by commit `15af22fc22` which has been included in `socket.io@4.6.2` (released in May 2023). The fix was backported in the 2.x branch as well with commit `d30630ba10`. Users are advised to upgrade. Users unable to upgrade may attach a listener for the \"error\" event to catch these errors.\n\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Important",
			"cve": [
				{
					"text": "CVE-2024-38355 at SUSE",
					"href": "https://www.suse.com/security/cve/CVE-2024-38355/",
					"impact": "high",
					"cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				{
					"text": "CVE-2024-38355 at NVD",
					"href": "https://nvd.nist.gov/vuln/detail/CVE-2024-38355"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1226965",
					"href": "https://bugzilla.suse.com/1226965"
				}
			],
			"issued": {
				"date": "2024-06-26"
			},
			"updated": {
				"date": "2024-10-31"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:suse:sle-module-python3:15:sp6"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009856171",
						"comment": "SUSE Linux Enterprise Desktop 15 SP6 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009856172",
						"comment": "SUSE Linux Enterprise High Performance Computing 15 SP6 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009856323",
						"comment": "SUSE Linux Enterprise Module for Python 3 15 SP6 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009856174",
						"comment": "SUSE Linux Enterprise Server 15 SP6 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009856175",
						"comment": "SUSE Linux Enterprise Server for SAP Applications 15 SP6 is installed"
					}
				]
			},
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009948947",
						"comment": "pgadmin4-8.5-150600.3.6.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009948950",
						"comment": "pgadmin4-doc-8.5-150600.3.6.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009948952",
						"comment": "system-user-pgadmin-8.5-150600.3.6.1 is installed"
					}
				]
			}
		]
	}
}
