{
	"id": "oval:org.opensuse.security:def:202015801",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"Title": "CVE-2020-15801",
		"affected": {
			"family": "unix",
			"Platform": [
				"SUSE Linux Enterprise Desktop 11 SP2",
				"SUSE Linux Enterprise Desktop 11 SP3",
				"SUSE Linux Enterprise Desktop 11 SP4"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2020-15801",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15801",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2020-15801",
				"ref_url": "https://www.suse.com/security/cve/CVE-2020-15801",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "unknown",
				"ref_url": "https://lists.suse.com/archive/suse-security-announce/2007-Jun/0001.html",
				"source": "SUSE-SU"
			}
		],
		"Description": "\n    In Python 3.8.4, sys.path restrictions specified in a python38._pth file are ignored, allowing code to be loaded from arbitrary locations. The <executable-name>._pth file (e.g., the python._pth file) is not affected.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"Severity": "Important",
			"cve": {
				"text": "CVE-2020-15801",
				"href": "https://www.suse.com/security/cve/CVE-2020-15801/",
				"impact": "important"
			},
			"bugzilla": [
				{
					"text": "SUSE bug 1174241",
					"href": "https://bugzilla.suse.com/1174241"
				}
			],
			"issued": {
				"date": "2021-04-30"
			},
			"updated": {
				"date": "2022-02-17"
			},
			"affected_cpe_list": {
				"Cpe": [
					"cpe:/o:suse:suse_sled:11:sp2",
					"cpe:/o:suse:suse_sled:11:sp3",
					"cpe:/o:suse:suse_sled:11:sp4"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009073771",
						"comment": "SUSE Linux Enterprise Desktop 11 SP2 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009077540",
						"comment": "SUSE Linux Enterprise Desktop 11 SP3 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009117401",
						"comment": "SUSE Linux Enterprise Desktop 11 SP4 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009334122",
				"comment": "python is not affected"
			}
		]
	}
}
