{
	"id": "oval:org.opensuse.security:def:20131633",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"Title": "CVE-2013-1633",
		"affected": {
			"family": "unix",
			"Platform": [
				"SUSE Linux Enterprise Desktop 11 SP3"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2013-1633",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-1633",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2013-1633",
				"ref_url": "https://www.suse.com/security/cve/CVE-2013-1633",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SU-2014:0523-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2014-April/000785.html",
				"source": "SUSE-SU"
			}
		],
		"Description": "\n    easy_install in setuptools before 0.7 uses HTTP to retrieve packages from the PyPI repository, and does not perform integrity checks on package contents, which allows man-in-the-middle attackers to execute arbitrary code via a crafted response to the default use of the product.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"Severity": "Moderate",
			"cve": {
				"text": "CVE-2013-1633",
				"href": "https://www.suse.com/security/cve/CVE-2013-1633/",
				"impact": "moderate"
			},
			"bugzilla": [
				{
					"text": "SUSE bug 843759",
					"href": "https://bugzilla.suse.com/843759"
				}
			],
			"issued": {
				"date": "2021-04-30"
			},
			"updated": {
				"date": "2021-10-13"
			},
			"affected_cpe_list": {
				"Cpe": [
					"cpe:/o:suse:suse_sled:11:sp3"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009077540",
				"comment": "SUSE Linux Enterprise Desktop 11 SP3 is installed"
			},
			{
				"test_ref": "oval:org.opensuse.security:tst:2009567098",
				"comment": "python-setuptools-0.6c8-10.19.6.1 is installed"
			}
		]
	}
}
