{
	"id": "oval:org.opensuse.security:def:20134314",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2013-4314",
		"affected": {
			"family": "unix",
			"platform": [
				"openSUSE Leap 42.3"
			]
		},
		"reference": [
			{
				"ref_id": "CVE-2013-4314",
				"ref_url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4314",
				"source": "CVE"
			}
		],
		"description": "\n    The X509Extension in pyOpenSSL before 0.13.1 does not properly handle a '\\0' character in a domain name in the Subject Alternative Name field of an X.509 certificate, which allows man-in-the-middle attackers to spoof arbitrary SSL servers via a crafted certificate issued by a legitimate Certification Authority.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Moderate",
			"cve": [
				{
					"text": "CVE-2013-4314",
					"href": "https://www.suse.com/security/cve/CVE-2013-4314.html"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 839107",
					"href": "https://bugzilla.suse.com/839107"
				}
			],
			"issued": {},
			"updated": {},
			"affected_cpe_list": {}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009217547",
						"comment": "python-pyOpenSSL-16.0.0-4 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009151924",
						"comment": "python-pyOpenSSL is signed with openSUSE key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009159611",
				"comment": "openSUSE Leap 42.3 is installed"
			}
		]
	}
}
