{
	"id": "oval:org.opensuse.security:def:202439614",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2024-39614",
		"affected": {
			"family": "unix",
			"platform": [
				"openSUSE Leap 15.6"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2024-39614",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-39614",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2024-39614",
				"ref_url": "https://www.suse.com/security/cve/CVE-2024-39614",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SU-2024:2545-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2024-July/018995.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2024:2577-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2024-July/036097.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Important",
			"cve": [
				{
					"text": "CVE-2024-39614 at SUSE",
					"href": "https://www.suse.com/security/cve/CVE-2024-39614/",
					"impact": "high",
					"cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				{
					"text": "CVE-2024-39614 at NVD",
					"href": "https://nvd.nist.gov/vuln/detail/CVE-2024-39614"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1227590",
					"href": "https://bugzilla.suse.com/1227590"
				},
				{
					"text": "SUSE bug 1227595",
					"href": "https://bugzilla.suse.com/1227595"
				}
			],
			"issued": {
				"date": "2024-07-23"
			},
			"updated": {
				"date": "2024-07-23"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:opensuse:leap:15.6"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009875212",
						"comment": "python311-Django-4.2.11-150600.3.3.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009875285",
						"comment": "python311-Django is signed with openSUSE key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009864054",
				"comment": "openSUSE Leap 15.6 is installed"
			}
		]
	}
}
