{
	"id": "oval:org.opensuse.security:def:202341105",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"Title": "CVE-2023-41105",
		"affected": {
			"family": "unix",
			"Platform": [
				"openSUSE Tumbleweed"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2023-41105",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-41105",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2023-41105",
				"ref_url": "https://www.suse.com/security/cve/CVE-2023-41105",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-CU-2023:3261-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2023-October/016538.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2023:3939-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2023-October/016481.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2023:3943-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2023-October/031897.html",
				"source": "SUSE-SU"
			}
		],
		"Description": "\n    An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"Severity": "Moderate",
			"cve": {
				"text": "CVE-2023-41105 at NVD",
				"href": "https://nvd.nist.gov/vuln/detail/CVE-2023-41105",
				"impact": "moderate",
				"cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
			},
			"bugzilla": [
				{
					"text": "SUSE bug 1214693",
					"href": "https://bugzilla.suse.com/1214693"
				}
			],
			"issued": {
				"date": "2023-09-26"
			},
			"updated": {
				"date": "2024-04-18"
			},
			"affected_cpe_list": {
				"Cpe": [
					"cpe:/o:opensuse:tumbleweed"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798872",
						"comment": "python311-3.11.5-2.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798873",
						"comment": "python311-32bit-3.11.5-2.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798874",
						"comment": "python311-curses-3.11.5-2.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798875",
						"comment": "python311-dbm-3.11.5-2.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798876",
						"comment": "python311-idle-3.11.5-2.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798877",
						"comment": "python311-tk-3.11.5-2.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798878",
						"comment": "python311-x86-64-v3-3.11.5-2.1 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009634834",
				"comment": "openSUSE Tumbleweed is installed"
			}
		]
	}
}
